name: Generate icons JSON

on:
  push:
    branches:
      - main  # Change this to the name of your default branch

jobs:
  generate-icons-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @octokit/rest  # Install Octokit REST API client

      - name: Generate icons JSON
        run: |
          # Get list of all PNG files in the repository
          png_files=$(find . -type f -iname "*.png" -exec basename {} \;)
          
          # Create array of icon objects with filename and URL
          icons="\"icons\": ["
          for file in $png_files
          do
            name=$(basename "${file}")
            url=$(echo "https://raw.githubusercontent.com/${{ github.repository }}/main/${file}" | sed 's/ /%20/g')
            icon="{\"name\": \"$name\", \"url\": \"$url\"},"
            icons="$icons$icon"
          done
          icons="${icons%,}]"  # Remove the last comma from the string
          
          # Create JSON object with name, icon array, and description
          json="{\"name\": \"Icons for proxy apps \", $icons, \"description\": \"Icons for proxy apps rules\"}"
          
          # Write JSON object to file
          echo $json > icons.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Update icons.json
          add: 'icons.json'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically generated by GitHub
